# Generated by Django 5.2.8 on 2025-11-09 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ButtonClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("button_label", models.CharField(max_length=255)),
                ("page_path", models.CharField(max_length=500)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "button_clicks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("consultation_type", models.CharField(max_length=100)),
                ("consultation_reason", models.TextField()),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "consultation_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRSCalculationDetailed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("input_data", models.JSONField(default=dict)),
                ("crs_score", models.IntegerField()),
                ("category_breakdown", models.JSONField(default=dict)),
                (
                    "improvement_suggestions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "crs_calculations_detailed",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_path", models.CharField(max_length=500)),
                ("page_title", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "page_views",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathwayAdvisorSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "citizenship_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "residence_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "work_experience_years",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("language_tests", models.JSONField(default=list)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("has_canadian_relative", models.BooleanField(default=False)),
                ("has_job_offer", models.BooleanField(default=False)),
                ("has_canadian_experience", models.BooleanField(default=False)),
                ("has_police_record", models.BooleanField(default=False)),
                (
                    "available_funds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pathway_goal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pathway_specific_data", models.JSONField(default=dict)),
                ("eligibility_results", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pathway_advisor_submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_id", models.UUIDField(blank=True, null=True)),
                ("note_content", models.TextField()),
                (
                    "note_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("consultation", "Consultation"),
                            ("follow_up", "Follow Up"),
                            ("internal", "Internal"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_private", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_notes",
            },
        ),
        migrations.CreateModel(
            name="CRSCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("calculation_date", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField()),
                ("category_breakdown", models.JSONField(default=dict)),
                ("input_data", models.JSONField(default=dict)),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crs_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crs_calculations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consultation_type", models.CharField(max_length=100)),
                ("scheduled_datetime", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("questions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_bookings",
                        to="core.crscalculation",
                    ),
                ),
            ],
            options={
                "db_table": "consultation_bookings",
            },
        ),
        migrations.CreateModel(
            name="MarketplaceWaitlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("service_types", models.JSONField(default=list)),
                ("signup_date", models.DateTimeField(auto_now_add=True)),
                ("notified", models.BooleanField(default=False)),
                ("preferences", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_waitlist",
            },
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("markdown_content", models.TextField()),
                ("generation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "llm_model_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("satisfaction_rating", models.IntegerField(blank=True, null=True)),
                ("regeneration_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to="core.crscalculation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "roadmaps",
            },
        ),
        migrations.CreateModel(
            name="PDFGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("download_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_generations",
                        to="core.roadmap",
                    ),
                ),
            ],
            options={
                "db_table": "pdf_generations",
            },
        ),
        migrations.CreateModel(
            name="ServiceBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("information_session", "Information Session"),
                            ("settlement_support", "Settlement Support"),
                        ],
                        max_length=50,
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("scheduled_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("selected_services", models.JSONField(default=list)),
                (
                    "pricing_details",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("specific_topics", models.JSONField(default=list)),
                (
                    "arrival_details",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "service_bookings",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "target_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "target_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("planned_arrival_date", models.DateField(blank=True, null=True)),
                (
                    "current_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "immigration_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("language_preference", models.CharField(default="en", max_length=10)),
                ("notification_settings", models.JSONField(blank=True, default=dict)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("agent", "Agent"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
    ]
