# Generated by Django 5.2.8 on 2025-11-09 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRSCalculationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("user_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("current_step", models.CharField(default="user-info", max_length=50)),
                ("completed_steps", models.JSONField(default=list)),
                ("partial_data", models.JSONField(default=dict)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crs_calculation_sessions",
                "ordering": ["-last_activity"],
            },
        ),
    ]
