# Generated by Django 5.2.8 on 2025-11-09 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_crscalculationsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmigrationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("user_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("profile_data", models.JSONField(default=dict)),
                ("report_markdown", models.TextField()),
                (
                    "pdf_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pdf_path", models.CharField(blank=True, max_length=500, null=True)),
                ("pdf_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "pathway_goal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ai_model_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="immigration_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "immigration_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
