# Generated by Django 5.2.8 on 2025-11-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_immigrationreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathwayadvisorsubmission",
            name="current_step",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pathwayadvisorsubmission",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pathwayadvisorsubmission",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="pathwayadvisorsubmission",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
