# Generated by Django 5.2.8 on 2025-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pathwayadvisorsubmission_current_step_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("connected", "Connected"),
                    ("completed", "Completed"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
